name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app pandas selenium openpyxl webdriver-manager

      - name: Install dmgbuild
        run: |
          pip install dmgbuild

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Create .dmg with dmgbuild
        run: |
          dmgbuild -s dmg_settings.py "ParserZakupok" "ParserZakupok.dmg"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParserZakupok
          path: ParserZakupok.dmg
